const path = {
  webViewPolicy: 'web-view-policy',
  webViewProvise: 'web-view-provise',
  webViewIntroduce: 'web-view-introduce',
  dashboards: '/dashboards',
  project: '/project',
  createProject: '/project/create',
  editProject: '/project/:id',
  transactionManagementProject: '/project/transaction-management/:id',
  createReservation: '/project/transaction-management/:id/reservation/create',
  editReservation:
    '/project/transaction-management/:id/reservation/:reservationId/edit',
  copyReservation:
    '/project/transaction-management/:id/reservation/:reservationId/copy',
  projectSetting: '/project/project-setting/:id',
  createSalesProgram: '/project/project-setting/:id/sales-program/create',
  editSalesProgram:
    '/project/project-setting/:id/sales-program/edit/:salesprogramId',
  processManagement: '/process-management',
  createProcessManagement: '/process-management/create',
  productTableSetting: '/project/product-table-setting/:id',
  editProcessManagement: '/process-management/edit/:id',
  copyProcessManagement: '/process-management/copy/:id',
  Comisstion: '/comisstions',
  ComisstionsRequest: '/comisstions/comisstions-request',
  editComisstionsRequest: '/comisstions/comisstions-request/:id',
  ComisstionsAccount: '/comisstions/comisstions-account',
  ComisstionRules: '/comisstions/comisstions-policy',
  createComisstionRules: '/comisstions/comisstions-policy/create',
  editComisstionRules: '/comisstions/comisstions-policy/:id',
  uploadComisstion: '/comisstions/comisstions-account/upload',
  ComisstionDetail: '/comisstions/comisstions-detail/:id',
  editComisstion: '/comisstions/comisstions-account/edit/:id',
  customer: '/customer',
  potentialAccount: '/customer/customers-potential',
  logImportCustomer: '/customer/logs-import',
  createCustomer: '/customer/customers-potential/create',
  customerDetail: '/customer/customers-potential/detail',
  customerTransaction: '/customer/customers-transaction',
  editCustomer: '/customer/customers-potential/:id',
  cityStarCustomer: '/customer/citystar',
  cityStarMembership: '/customer/membrship',
  cityStarWelcome: '/citystar/welcome/:id',
  cityStarRegisterSuccess: '/citystar/membership-active/:id',
  creataCityStarMembrship: '/citystar/membership',
  cityStar: '/citystar',
  cityStarPolicy: '/citystar/policy',
  transaction: '/transaction',
  carrers: '/carrers',
  createCarrers: '/carrers/create',
  carrersDetail: '/carrers/detail/:id',
  editCarrers: '/carrers/edit/:id',
  kpi: '/kpi',
  kpiPotentialCustomers: '/kpi/:id',
  createKpiMission: '/kpi-mission/create',
  editKpiMission: '/kpi-mission/edit/:id',
  Orgcharts: '/orgchart',
  createOrgchart: '/orgchart/create',
  OrgchartDetail: '/orgchart/detail/:id',
  editOrgchart: '/orgchart/edit/:id',
  settings: '/setting',
  liquidContract: '/contracts/liquid/:id',
  appendixContract: '/contracts/appendix/:id',
  createContract: '/contracts/create',
  staff: '/staff',
  createStaff: '/staff/create',
  StaffDetail: '/staff/:id',
  Profile: '/profile',
  roleList: '/setting/roleList',
  permission: '/setting/permission',
  contentManagement: '/setting/content',
  createpermission: '/setting/permission/create',
  detailViewValuation: '/staff/list-detail/:id',
  workingValuation:
    '/staff/list-detail/:contractId/working-valuation/:appraisalId',
  appraisalValuation: '/staff-contract/:contractId/appraisal/:appraisalId',
  reports: '/reports',
  leads: '/leads',
  leadManagement: '/leads/management',
  leadsCare: '/leads/takecare',
  financeStaff: '/finances/staff',
  financeStaffDetail: '/finances/staff/:id',
  createCategory: '/category/create',
  detailCategory: '/category/detail/:id',
  editCategory: '/category/edit/:id',
  login: '/auth/login',
  updatePassword: '/update-password',
  notFound: '/not-found',
  groundEsalekit: '/ground-esalekit/:id',
  esalekit: '/esalekit',
  esalekitOverview: '/esalekit/overview/:id',
  esalekitPreview: '/esalekit/preview/:id',
  esalekitGround: '/esalekit/ground',
  esalekUtilities: '/esalekit/utilities',
  esalekitLibrary: '/esalekit/library',
  esalekitPolicy: '/esalekit/policy',
  esalekitNews: '/esalekit/news',
  managementInformation: 'project/:projectID/management-information',
  payment: 'payments',
  receipts: 'payments/receipts',
  refunds: 'payments/refunds',
  cancellationTicket: 'payments/cancellation-ticket',
  saleEvent: '/sale-event',
  saleEventControl: '/sale-event/:id/control',
  saleEventTransaction: '/sale-event/project/:projectId/transaction/:transactionId',
  termCondition: '/term-condition',
  virtualTable: '/sale-event/project/:projectId/transaction/:id/virtual',
  virtualTableView:
    '/sale-event/project/:projectId/transaction/:id/virtual/view',
  root: '/',
  all: '*',
};

export default path;
